from enum import Enum

class Currencies(Enum):
    USD = "usd"
    GBP = "gbp"
    INR = "inr"
    AUD = "aud"
    CAD = "cad"
    CHF = "chf"
    JPY = "jpy"
    CNY = "cny"
    BRL = "brl"
    RUB = "rub"
    KRW = "krw"
    MXN = "mxn"
    ZAR = "zar"
    NOK = "nok"
    SGD = "sgd"
    NZD = "nzd"
    HKD = "hkd"
    SEK = "sek"
    TRY = "try"
    DKK = "dkk"
    PLN = "pln"
    THB = "thb"
    IDR = "idr"
    MYR = "myr"
    PHP = "php"
    TWD = "twd"
    SAR = "sar"
    AED = "aed"
    ILS = "ils"
    VND = "vnd"
